import "~/styles/globals.css";

import { TRPCReactProvider } from "~/trpc/react";
import { Header } from "~/app/_components/Header";
import { GoBack } from "./_components/GoBack";

import {Libre_Franklin,IBM_Plex_Mono} from 'next/font/google'

export const libre = Libre_Franklin ({
    subsets: ["latin"],
    weight: '600',
    variable: "--font-heading",
})

export const ibm = IBM_Plex_Mono({
    subsets: ["latin"],
    weight: '400',
    variable: "--font-text",
})
export const metadata = {
  title: "Neddy Bikes",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${ibm.variable} ${libre.variable} min-h-screen`}>
      <body className="grid grid-cols-12">
        <TRPCReactProvider>
          <Header />
          <div className="col-span-12 container flex justify-start">
            <GoBack />
          </div>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
