import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { Header } from "~/app/_components/Header";
import { GoBack } from "./_components/GoBack";

export const metadata = {
  title: "Neddy Bikes",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} min-h-screen`}>
      <body className="grid grid-cols-12">
        <TRPCReactProvider>
          <Header />
          <div className="col-span-12 container flex justify-start">
            <GoBack />
          </div>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
